from turtle import *
screen = Screen()
t = Pen()
t.pu()
screen.onscreenclick(t.goto)          
t.speed(0)
def cl():
    t1 = t.clone()
    t2 = t.clone()
    t3 = t.clone()
    t4 = t.clone()
    t1.forward(10)
    x,y = t2.pos()
    t2.goto(x,y+10)
    x,y = t3.pos()
    t3.goto(x,y-10)
    t.forward(-10)
    t1 = t.clone()
    t.goto(999,999)
listen()
screen.onkey(cl,'w')
mainloop()